"""Performance assets, generated (not hand-edited):

  assets/fa/        Font Awesome 6.4 subset: only the icons actually used on the site
  assets/fonts/     Self-hosted Inter Tight + Instrument Sans (latin), OFL licensed
  assets/*.webp     WebP copies of every raster image in use (originals stay for
                    social previews and structured data)

Downloads are cached in tools/.cache. Run via tools/build.py.
"""
import glob
import io
import json
import os
import re
import sys
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
CACHE = os.path.join('tools', '.cache')
os.makedirs(CACHE, exist_ok=True)

UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
FA = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0'


def get(url, name=None, ua=False):
    path = os.path.join(CACHE, name or re.sub(r'[^A-Za-z0-9._-]', '_', url)[-120:])
    if not os.path.exists(path):
        req = urllib.request.Request(url, headers={'User-Agent': UA} if ua else {})
        open(path, 'wb').write(urllib.request.urlopen(req, timeout=60).read())
    return open(path, 'rb').read()


def source_files():
    pats = ['index.html', 'articles.html', 'app.js', 'content/*.json', 'content/*.py', 'tools/build_*.py']
    out = []
    for p in pats:
        out += glob.glob(p)
    return out


# ------------------------------------------------------------------ Font Awesome subset
def build_icons():
    css = get(f'{FA}/css/all.min.css', 'fa-all.min.css').decode('utf-8')
    codepoints = {}
    for sel, cp in re.findall(r'((?:\.fa-[a-z0-9-]+:before,?)+)\{content:"\\([0-9a-f]+)"\}', css):
        for name in re.findall(r'\.fa-([a-z0-9-]+):before', sel):
            codepoints[name] = cp

    used = {'fas': set(), 'far': set(), 'fab': set()}
    for f in source_files():
        text = open(f, encoding='utf-8', errors='ignore').read()
        for prefix, icon in re.findall(r'\b(fas|far|fab)\s+fa-([a-z0-9-]+)', text):
            used[prefix].add(icon)

    families = {'fas': ('fa-solid', 900, f'{FA}/webfonts/fa-solid-900.ttf'),
                'far': ('fa-regular', 400, f'{FA}/webfonts/fa-regular-400.ttf'),
                'fab': ('fa-brands', 400, f'{FA}/webfonts/fa-brands-400.ttf')}
    os.makedirs('assets/fa', exist_ok=True)
    manifest_path = 'assets/fa/icons-manifest.json'
    try:
        old_manifest = json.load(open(manifest_path, encoding='utf-8'))
    except (OSError, ValueError):
        old_manifest = {}
    new_manifest = {p: sorted(used[p]) for p in used}
    rules = []
    report = []
    for prefix, (fname, weight, url) in families.items():
        icons = sorted(used[prefix])
        unknown = [i for i in icons if i not in codepoints]
        if unknown:
            sys.exit(f'Unknown Font Awesome icons for {prefix}: {unknown}')
        cps = sorted({int(codepoints[i], 16) for i in icons})
        out = f'assets/fa/{fname}.woff2'
        if old_manifest.get(prefix) == new_manifest[prefix] and os.path.exists(out):
            report.append(f'{fname}: unchanged ({len(icons)} icons)')   # keep the committed font bytes stable
            for i in icons:
                rules.append(f'.fa-{i}:before{{content:"\\{codepoints[i]}"}}')
            continue
        src = get(url, f'{fname}.ttf')
        font = TTFont(io.BytesIO(src))
        have = set(font.getBestCmap())
        missing = [hex(c) for c in cps if c not in have]
        if missing:
            sys.exit(f'{prefix}: glyphs missing from the font for {missing}')
        opts = subset.Options()
        opts.flavor = 'woff2'
        opts.layout_features = []
        opts.name_IDs = []
        opts.notdef_outline = True
        sub = subset.Subsetter(opts)
        sub.populate(unicodes=cps)
        sub.subset(font)
        out = f'assets/fa/{fname}.woff2'
        font.flavor = 'woff2'
        font.save(out)
        report.append(f'{fname}: {len(icons)} icons, {len(src)//1024} KB -> {os.path.getsize(out)/1024:.1f} KB')
        for i in icons:
            rules.append(f'.fa-{i}:before{{content:"\\{codepoints[i]}"}}')

    with open(manifest_path, 'w', encoding='utf-8', newline='\n') as mf:
        json.dump(new_manifest, mf, indent=1)
    css_out = '''/* Generated by tools/build_assets.py - Font Awesome Free 6.4 (CC BY 4.0 icons, SIL OFL fonts), subset to the icons in use. */
@font-face{font-family:"Font Awesome 6 Brands";font-style:normal;font-weight:400;font-display:block;src:url(fa-brands.woff2) format("woff2")}
@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:400;font-display:block;src:url(fa-regular.woff2) format("woff2")}
@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url(fa-solid.woff2) format("woff2")}
.fa,.fab,.far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}
.fas{font-family:"Font Awesome 6 Free";font-weight:900}
.far{font-family:"Font Awesome 6 Free";font-weight:400}
.fab{font-family:"Font Awesome 6 Brands";font-weight:400}
''' + '\n'.join(rules) + '\n'
    open('assets/fa/fa-subset.css', 'w', encoding='utf-8', newline='\n').write(css_out)
    print('icons  :', '; '.join(report))


# ------------------------------------------------------------------ self-hosted fonts
def build_fonts():
    q = 'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&family=Instrument+Sans:wght@400;500;600;700&display=swap'
    css = get(q, 'google-fonts.css', ua=True).decode('utf-8')
    os.makedirs('assets/fonts', exist_ok=True)
    blocks = re.findall(r'/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    out = ['/* Generated by tools/build_assets.py - Inter Tight and Instrument Sans (SIL OFL), latin subset, self-hosted. */']
    files = {}
    for subset_name, block in blocks:
        if subset_name != 'latin':
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r'font-weight:\s*([\d ]+);', block).group(1).strip()
        url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
        slug = fam.lower().replace(' ', '-')
        key = (slug, url)
        if key not in files:
            files[key] = f'{slug}-{len(files) + 1}.woff2'
            open(f'assets/fonts/{files[key]}', 'wb').write(get(url, files[key]))
        out.append(f'@font-face{{font-family:"{fam}";font-style:normal;font-weight:{weight};font-display:swap;src:url({files[key]}) format("woff2")}}')
    open('assets/fonts/fonts.css', 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    total = sum(os.path.getsize(f'assets/fonts/{n}') for n in files.values())
    print(f'fonts  : {len(files)} files, {total//1024} KB (latin)')


# ------------------------------------------------------------------ WebP copies
def build_webp():
    used = set()
    for f in glob.glob('**/*.html', recursive=True) + glob.glob('*.js') + glob.glob('content/*') + glob.glob('tools/build_*.py'):
        text = open(f, encoding='utf-8', errors='ignore').read()
        used.update(re.findall(r'assets/([A-Za-z0-9_\-]+\.(?:jpg|jpeg|png))', text))
    made = saved = 0
    for name in sorted(used):
        src = os.path.join('assets', name)
        if not os.path.exists(src):
            continue
        dst = os.path.splitext(src)[0] + '.webp'
        if os.path.exists(dst) and os.path.getmtime(dst) >= os.path.getmtime(src):
            continue
        im = Image.open(src)
        if im.mode not in ('RGB', 'RGBA'):
            im = im.convert('RGBA' if 'transparency' in im.info else 'RGB')
        im.save(dst, 'WEBP', quality=80, method=6)
        made += 1
        saved += os.path.getsize(src) - os.path.getsize(dst)
    print(f'webp   : {made} new, saved {saved//1024} KB vs originals')


def build_favicons():
    """Square icons from the logo emblem (Google wants a square favicon, multiples of 48px)."""
    im = Image.open('assets/real_logo.png').convert('RGBA')
    alpha = im.split()[3]
    cols = [x for x in range(im.width) if any(alpha.getpixel((x, y)) > 40 for y in range(0, im.height, 2))]
    run = [cols[0]]
    for c in cols[1:]:
        if c - run[-1] > 6:
            break
        run.append(c)
    x0, x1 = run[0], run[-1] + 1
    rows = [y for y in range(im.height) if any(alpha.getpixel((x, y)) > 40 for x in range(x0, x1))]
    emblem = im.crop((x0, rows[0], x1, rows[-1] + 1))
    side = max(emblem.size)
    sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
    sq.paste(emblem, ((side - emblem.width) // 2, (side - emblem.height) // 2))
    os.makedirs('assets/icons', exist_ok=True)
    sq.resize((192, 192), Image.LANCZOS).save('assets/icons/icon-192.png', optimize=True)
    sq.resize((48, 48), Image.LANCZOS).save('assets/icons/icon-48.png', optimize=True)
    touch = Image.new('RGB', (180, 180), (255, 255, 255))
    inner = sq.resize((156, 156), Image.LANCZOS)
    touch.paste(inner, (12, 12), inner)
    touch.save('assets/icons/apple-touch-icon.png', optimize=True)
    sq.resize((48, 48), Image.LANCZOS).save('favicon.ico', sizes=[(16, 16), (32, 32), (48, 48)])
    print('favicon: icon-48/192, apple-touch-icon, favicon.ico')


def build_hero_bg():
    """Pre-blurred backdrop for the hero card (cheaper and smoother than a live CSS blur)."""
    from PIL import ImageEnhance, ImageFilter
    src = 'assets/real_app_commercial.jpg'
    if not os.path.exists(src):
        return
    dst = 'assets/hero-bg.webp'
    if os.path.exists(dst) and os.path.getmtime(dst) >= os.path.getmtime(src):
        return
    im = Image.open(src).convert('RGB').resize((640, 384), Image.LANCZOS).filter(ImageFilter.GaussianBlur(9))
    im = ImageEnhance.Color(im).enhance(1.15)
    im.save(dst, 'WEBP', quality=62, method=6)
    print('hero-bg: %d KB' % (os.path.getsize(dst) // 1024))


def main():
    build_hero_bg()
    build_favicons()
    build_icons()
    build_fonts()
    build_webp()


if __name__ == '__main__':
    main()
